### ISSUE TITLE
Can't read names in sidebar if they have a clan tag

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#123]
ZmTeam members frequently have no name.  It's not uncommon to see "Dr. <ZmTeam> ..." so you can't call the person by name without memorizing who they are, etc...

It shouldn't be too hard to remove the clan tag from the naming scheme on the HP bar.

**Comment by ReduxGelum** [comment]
Same problem with other clan tags as well, when blizz changed delimiters to "<" and ">" it got bad. My suggestion is just get rid of any prefix "<blahblah> " at the start of the name, tags are visible in chat anyway.
