### ISSUE TITLE
New shop ui things

### ISSUE THREAD

**Issue by NiktosNOTD** [ArcanePariah/Night-of-the-Dead#190]
So new shop is online. Appears bugfree when it comes to standard functionality.

Issues i found:
1.I forgot -recruit games had access to permanent items shop. Mine is fully inacessible there.
To fix, rewrite to be accessible in recruit just disable buying of one game items.
2.Trigger responsible for closing shop when someone walks away is initially on. regardles of shop being accessible or not.

**Comment by ThunderRazor** [comment]
Before you close down old shop, will you please add in all the item properties (and quotes) displayed from old shop items to the new shop items? Make them consistent please since the quotes are part of the story.

**Comment by NiktosNOTD** [comment]
Both properties and quotes were removed as imo they were visually bloating up tooltip.
In my understanding they are there only coz old shop uses same tooltips as button hover of item. As in same entry not even copy-paste they just point to same thing.

I don't mind re-adding the quotes in smaller font at end, properties don't seem needed.
For now i only fixed 2 above bugs. Removing old one is not pressing issue, so it will wait some more definitely.

**Comment by NiktosNOTD** [comment]
So in pull #232 I re-add the flavour texts. Doing it reminded me why i removed them in the first place.
They are inconsistent, some have "- author" some don't, and also for almost half of shop items they don't exist at all.

Anyway they will be there again, after it goes live i will submit the removal of old shop as well as -noshop command, also as lobby attribute coz with old shop functional adding -noshop gets unnecessarily complicated.

**Comment by NiktosNOTD** [comment]
Pull #241 clears up last issue of new shop not working in recruit mode so the issue will be fixed once, it is merged.
