### ISSUE TITLE
Delta-2 Civilians in Alpha only supply 3 controllable civilians

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#32]
The other 3 civs are owned by some other player and can't be saved.  I would also recommend the window to save them be drastically increased/opened forever so that people can attempt to save them at any time.

**Comment by dave-sWpR46Ae** [comment]
Additionally, 52 civilians total seems a little low and may need to be bumped to 56 or so.  The civilians should all spawn at once, 13-14 at each of the 4 houses rather than the current randomization.

There are also houses near the reactor in Security A that could theoretically be used to save civilians in addition to the survivors from Nakagawa bay.

**Comment by ReduxGelum** [comment]
Agree with 52 being too little, also agree with delta fix.

**Comment by ReduxGelum** [comment]
Added a pull request that fixes the issue and ups the delta civs to 12 from 6.

**Comment by dave-sWpR46Ae** [comment]
Fixed #40
