### ISSUE TITLE
[All] L3 grenade doesn't share XP

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#34]
Is it possible to make the L3 share XP?  It's already hardly used because it is now the "L5" and costs 5 ammo instead of 3.

**Comment by NiktosNOTD** [comment]
It's funnier, l3 shares xp. It just does it wrong.
To expand on it, share point is on grenade itself not the attacking marine. Enemies killed close give share xp no prob, far kills end up out of range. Considering how l3 works (mostly far kills during spam) it's easy to miss this in normal game and simply assume it's broken.
I don't feel ready to mess with triggers but this hint might help someone who does.

**Comment by dave-sWpR46Ae** [comment]
ReduxGelum/Stank made a post on the forums about XP and how it's shared.

Easy fix is to make l3 share XP globally or increase the radius of the share to 40 or so.

Easiest fix is to remove l3 from the game.

**Comment by ReduxGelum** [comment]
To fix you need to mess with data, not triggers.

At some point AP moved everything to data, in retrospect it had multiple side effects.
