### ISSUE TITLE
Automatic Reloads happen extremely quickly when using fast attacks

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#51]
When you shoot a weapon, it checks if it's a shotgun, stinger, or barrett first, else subtracts 1 from ammo count.  Then it calls the following trigger:

gf_AmmoUsage(lv_attackingPlayer, lv_firingUnit, ge_ReloadType_Automatic, lv_attackingWeapon);

void gf_AmmoUsage (int lp_player, unit lp_attackingUnit, int lp_reload, string lp_weapon) {
    // Implementation
    gf_UpdateAmmoDialog(lp_player);
    gf_ActivateDeactiveReload(lp_player, lp_attackingUnit);
    Wait(1.0, c_timeGame);
    if ((gv_marineRounds[lp_player] <= 0) && (gv_reloading[lp_player] == false)) {
        if ((gv_marineMags[lp_player] <= 0)) {
            UnitBehaviorAddPlayer(lp_attackingUnit, "InsufficientAmmo", lp_player, 1);
            gf_OutofAmmoMessage(lp_attackingUnit);
        }
        else {
            UnitIssueOrder(lp_attackingUnit, Order(AbilityCommand("move", 2)), c_orderQueueReplace);
            gf_ReloadMagazine(lp_player, lp_attackingUnit, lp_reload, lp_weapon);
        }
    }
    else {
        if (((gv_marineMags[lp_player] >= 1) && (gv_marineMags[lp_player] <= 3)) && (UnitIsAlive(lp_attackingUnit) == true)) {
            gf_LowAmmoMessage(lp_attackingUnit);
        }
        else {
        }
    }
}

I believe what may be happening is that the Wait(1.0, c_timeGame); is running from a previous shot, causing weapons that shoot faster than once per game second to white reload quickly.

**Comment by dave-sWpR46Ae** [comment]
We will leave this open to migrate to data rather than trigger based ammo, which will hopefully also solve the doubleshot bug.  Pull request #52 is opened for this and splits the wait into 0.3/0.7 seconds.

**Comment by ReduxGelum** [comment]
The issue with reload is now fixed. 
The workaround doesn't fix everything with ammo, that would need a rewrite of ammo system, but the main issue with premature reloads is solved.
