### ISSUE TITLE
Autocast doesn't work

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#55]
Since I didn't test autocast (it was made before I knew how to test), looks like it's got major issues.

A major oversight on my part is that NOTD skill buttons DISAPPEAR FOR NO REASON.  I have no clue in the editor why this happens, and apparently AP fixed BHS and cloak the last time.  In order to get autocast to even approach working correctly, we need to remove this bullshit from the game first.

Additionally, bloodlust for some silly reason doesn't actually fire on autocast.  The duration lasts less than a second and the icon doesn't disappear.

Iron hand applies the -5 second slowdown but never speeds up the attack.

Focus fire seems to work perfectly.

Stealth can never be toggled off until you run out of energy.

**Comment by ArcanePariah** [comment]
The disappear is a product of the ability type.

Behavior type abilities have 2 commands, one to apply the behavior, one to remove it. In NOTD, in most cases, the behaviors are timed, and thus the button comes back after the behavior wears off.

To change this, you can use an Effect - Instant type ability instead, which will use an Apply Behavior effect to actually apply the behavior.

**Comment by ArcanePariah** [comment]
I would caution on the usage of Effect - Instant because it does have balance implications. Due to the button disappearing, you can not preemptively cast the effect to refresh the behavior before it is expired.

**Comment by ReduxGelum** [comment]
If the type is what preventing autocast, then types will have to be fixed. I think the behavior abilities are erroneously used on things that aren't behavior abilities.

I can understand recon cloak having this for example, cos he has a separate decloak button. But how does rifleman bloodlust factor into this? We cant and don't want to turn off bloodlust, in every sense it should be identical to focus fire -- you click button, unit gets temporary buff. You don't need a button to deactivate the behavior.

I doubt there are any balance issues, if some skill suddenly becomes more spam-able, cooldowns should be added identical to existing behavior timeouts.

**Comment by dave-sWpR46Ae** [comment]
There's 1 ability that would be affected: stealth.  It has a cooldown of 11 and duration of 12.  The cooldown is completely useless, as you can't actually cast steath again until you're unstealthed at 12 seconds.

**Comment by dave-sWpR46Ae** [comment]
List of Ability Behaviors that I'm willing to do and add autocast to:
Bloodlust
Taunt
Frenzy
IYF
Turbo
Targeting Computer
Iron Hand
Stealth

The other Ability Behaviors (like BHS) aren't huge.  It's dumb that they disappear, but this is a minor change that only affects future proofing.
