### ISSUE TITLE
Infestor spawns

### ISSUE THREAD

**Issue by ReduxGelum** [ArcanePariah/Night-of-the-Dead#77]
Infestors don't spawn extra enemies while alive.

http://notdstarcraft.com/threads/infestor-spawns.3736/

**Comment by dave-sWpR46Ae** [comment]
I think this is fixed, can we close?

**Comment by ReduxGelum** [comment]
Need to update spawns so enemies don't appear in closed off areas.

**Comment by ReduxGelum** [comment]
Spawns are fixed and Infestors behave just like they did in old versions of the map, this is fixed.
